# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zone.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nzone.proto\"W\n\x07ZoneReq\x12\x0b\n\x03zid\x18\x01 \x01(\t\x12\r\n\x05zname\x18\x02 \x01(\t\x12\x0b\n\x03zip\x18\x03 \x01(\t\x12\x13\n\x0bzsvnversion\x18\x04 \x01(\t\x12\x0e\n\x06target\x18\x05 \x01(\t\"C\n\x08ZoneResp\x12\x0b\n\x03zid\x18\x01 \x01(\t\x12\r\n\x05zname\x18\x02 \x01(\t\x12\x0b\n\x03zip\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\t2,\n\x04Zone\x12$\n\x0bzone_option\x12\x08.ZoneReq\x1a\t.ZoneResp\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zone_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ZONEREQ._serialized_start=14
  _ZONEREQ._serialized_end=101
  _ZONERESP._serialized_start=103
  _ZONERESP._serialized_end=170
  _ZONE._serialized_start=172
  _ZONE._serialized_end=216
# @@protoc_insertion_point(module_scope)
