// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mwire

import (
	"show/internal/api"
	"show/internal/app"
	"show/internal/dao"
	"show/internal/service"
)

// Injectors from wire.go:

func InitializeServer() *app.HTTPServer {
	userDAO := dao.NewUserDAO()
	userService := service.NewUserService(userDAO)
	userController := api.NewUserController(userService)
	v := provideApis(userController)
	httpServer := app.NewHTTPServer(v)
	return httpServer
}
