// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: zone.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip         string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Zid        string `protobuf:"bytes,3,opt,name=zid,proto3" json:"zid,omitempty"`
	Target     string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	SvnVersion uint64 `protobuf:"varint,5,opt,name=svnVersion,proto3" json:"svnVersion,omitempty"`
}

func (x *ZoneRequest) Reset() {
	*x = ZoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zone_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneRequest) ProtoMessage() {}

func (x *ZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneRequest.ProtoReflect.Descriptor instead.
func (*ZoneRequest) Descriptor() ([]byte, []int) {
	return file_zone_proto_rawDescGZIP(), []int{0}
}

func (x *ZoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ZoneRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ZoneRequest) GetZid() string {
	if x != nil {
		return x.Zid
	}
	return ""
}

func (x *ZoneRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ZoneRequest) GetSvnVersion() uint64 {
	if x != nil {
		return x.SvnVersion
	}
	return 0
}

type ZoneReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Zid    string `protobuf:"bytes,3,opt,name=zid,proto3" json:"zid,omitempty"`
	Target string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Ip     string `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *ZoneReply) Reset() {
	*x = ZoneReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zone_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZoneReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneReply) ProtoMessage() {}

func (x *ZoneReply) ProtoReflect() protoreflect.Message {
	mi := &file_zone_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneReply.ProtoReflect.Descriptor instead.
func (*ZoneReply) Descriptor() ([]byte, []int) {
	return file_zone_proto_rawDescGZIP(), []int{1}
}

func (x *ZoneReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ZoneReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ZoneReply) GetZid() string {
	if x != nil {
		return x.Zid
	}
	return ""
}

func (x *ZoneReply) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ZoneReply) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_zone_proto protoreflect.FileDescriptor

var file_zone_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x7a, 0x6f, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x7b, 0x0a, 0x0b, 0x5a, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x7a, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x7a, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x76, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x76, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x71, 0x0a, 0x09, 0x5a, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x7a,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x7a, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x70, 0x32, 0x3d, 0x0a, 0x04, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x35, 0x0a,
	0x07, 0x4f, 0x70, 0x74, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x5a, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x5a, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_zone_proto_rawDescOnce sync.Once
	file_zone_proto_rawDescData = file_zone_proto_rawDesc
)

func file_zone_proto_rawDescGZIP() []byte {
	file_zone_proto_rawDescOnce.Do(func() {
		file_zone_proto_rawDescData = protoimpl.X.CompressGZIP(file_zone_proto_rawDescData)
	})
	return file_zone_proto_rawDescData
}

var file_zone_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zone_proto_goTypes = []interface{}{
	(*ZoneRequest)(nil), // 0: service.ZoneRequest
	(*ZoneReply)(nil),   // 1: service.ZoneReply
}
var file_zone_proto_depIdxs = []int32{
	0, // 0: service.Zone.OptZone:input_type -> service.ZoneRequest
	1, // 1: service.Zone.OptZone:output_type -> service.ZoneReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zone_proto_init() }
func file_zone_proto_init() {
	if File_zone_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zone_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zone_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZoneReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zone_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zone_proto_goTypes,
		DependencyIndexes: file_zone_proto_depIdxs,
		MessageInfos:      file_zone_proto_msgTypes,
	}.Build()
	File_zone_proto = out.File
	file_zone_proto_rawDesc = nil
	file_zone_proto_goTypes = nil
	file_zone_proto_depIdxs = nil
}
