// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: zone.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ZoneClient is the client API for Zone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZoneClient interface {
	// 区服操作
	OptZone(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (*ZoneReply, error)
}

type zoneClient struct {
	cc grpc.ClientConnInterface
}

func NewZoneClient(cc grpc.ClientConnInterface) ZoneClient {
	return &zoneClient{cc}
}

func (c *zoneClient) OptZone(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (*ZoneReply, error) {
	out := new(ZoneReply)
	err := c.cc.Invoke(ctx, "/service.Zone/OptZone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZoneServer is the server API for Zone service.
// All implementations must embed UnimplementedZoneServer
// for forward compatibility
type ZoneServer interface {
	// 区服操作
	OptZone(context.Context, *ZoneRequest) (*ZoneReply, error)
	mustEmbedUnimplementedZoneServer()
}

// UnimplementedZoneServer must be embedded to have forward compatible implementations.
type UnimplementedZoneServer struct {
}

func (UnimplementedZoneServer) OptZone(context.Context, *ZoneRequest) (*ZoneReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OptZone not implemented")
}
func (UnimplementedZoneServer) mustEmbedUnimplementedZoneServer() {}

// UnsafeZoneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZoneServer will
// result in compilation errors.
type UnsafeZoneServer interface {
	mustEmbedUnimplementedZoneServer()
}

func RegisterZoneServer(s grpc.ServiceRegistrar, srv ZoneServer) {
	s.RegisterService(&Zone_ServiceDesc, srv)
}

func _Zone_OptZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServer).OptZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Zone/OptZone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServer).OptZone(ctx, req.(*ZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zone_ServiceDesc is the grpc.ServiceDesc for Zone service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zone_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Zone",
	HandlerType: (*ZoneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OptZone",
			Handler:    _Zone_OptZone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zone.proto",
}
